services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true
  App\:
    resource: '../src/*'
    exclude: '../src/{GraphQL/Resolver,Kernel.php}'

  # Remove the following if you dont want to use GraphQL
  App\Subscriber\GraphQLResolverSubscriber:
    tags:
      - 'kernel.event_subscriber'